# This is a basic workflow to help you get started with Actions (Dummy dumb)

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Godot export by firebelley
      - name: Godot Export
        uses: firebelley/godot-export@v4.1.0
        with:
          # The download url of the Linux Headless Godot executable.
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_linux_headless.64.zip
          # The url of the export templates corresponding to the Godot executable version.
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_export_templates.tpz
          # The path relative to the root of the git repository that contains the "project.godot" file.
          relative_project_path: ./
          # If provided, exports will be moved to this directory relative to the root of the Git repository. This setting is overridden by "use_preset_export_path".
          relative_export_path: ./build/ # optional, default is 
          # If "true" Godot will export in debug mode.
          export_debug: true
